---
- name: "Debian: Install development packages"
  become: yes
  apt:
    state: present
    update_cache: yes
    name:
      - autoconf
      - automake
      - bison
      - flex
      - gcc
      - git
      - libevent-dev
      - libfuse-dev
      - libgc-dev
      - libjansson-dev
      - libkrb5-dev
      - libncurses5-dev
      - libperl-dev
      - libssl-dev
      - libtool
      - make
      - swig
      - wget
      - build-essential
      - fakeroot
      - devscripts
      - lintian
      - libpod-parser-perl
      # Required for docs
      - dblatex
      - docbook-xsl
      - libxml2-utils
      - xsltproc
  tags: root
